- hosts: all
  remote_user: me
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: sync master db to local db
      shell: rsync -a {{db_mount_dir}}/pgdata/ {{local_mount_dir}}/pgdata/
