- hosts: all
  remote_user: me
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: start postgis
      shell: ./docker-compose up -d postgis chdir={{install_dir}}
